import TelegramBot from 'node-telegram-bot-api';
import { GoogleGenAI } from '@google/genai';
import { instagramGetUrl } from 'instagram-url-direct';
import express from 'express';
import dotenv from 'dotenv';
import PDFDocument from 'pdfkit';
import nodemailer from 'nodemailer';

dotenv.config();

// --- Email Transporter Setup ---
const transporter = nodemailer.createTransport({
  // Direct IPv4 address for smtp.gmail.com to bypass broken IPv6 resolution
  host: '74.125.20.108', 
  port: 465,
  secure: true,
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  },
  tls: {
    // This tells the mail server we know we are using an IP instead of 'smtp.gmail.com'
    servername: 'smtp.gmail.com', 
    rejectUnauthorized: false
  }
});

const bot = new TelegramBot(process.env.TELEGRAM_BOT_TOKEN, { polling: true });
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

const userMemory = new Map(); 
const stoppedUsers = new Set();
const pendingRequests = new Map();

// Stable 2026 Models
const VISION_MODEL = 'gemini-2.5-flash'; 
const TEXT_MODEL = 'gemini-3.1-flash-lite-preview'; 

console.log("🤖 Unified Bot: Requirements Merged & Stable.");

// --- Chunking Fix for Telegram ---
async function sendSafeMessage(chatId, text) {
  const MAX_LENGTH = 4000;
  if (text.length <= MAX_LENGTH) return bot.sendMessage(chatId, text);
  const chunks = text.match(/[^]{1,4000}/g) || [];
  for (const chunk of chunks) {
    await bot.sendMessage(chatId, chunk);
    await new Promise(r => setTimeout(r, 500)); 
  }
}

// --- AI Merged Logic ---
async function analyzeVision(base64ImagesArray, userPrompt) {
  let finalPrompt = "";

  if (userPrompt) {
    // If you ask a specific question, answer it, but ALSO write down the rest of the details for memory.
    finalPrompt = `User's primary request: "${userPrompt}"\n\nFirst, fulfill the user's primary request directly. Then, add a section called "--- HIDDEN CONTEXT ---" and describe all other visual details and text in these images so you can remember them for future questions.`;
  } else {
    // If you just send a link, do the standard full scan.
    finalPrompt = "Describe this post in detail and extract all text.";
  }

  const result = await ai.models.generateContent({
    model: VISION_MODEL,
    contents: [{
      role: 'user',
      parts: [
        { text: finalPrompt },
        ...base64ImagesArray.map(data => ({ inlineData: { mimeType: 'image/jpeg', data } }))
      ]
    }]
  });
  return result.text;
}

async function analyzeText(visualContext, userQuestion) {
  const result = await ai.models.generateContent({
    model: TEXT_MODEL,
    contents: [{
      role: 'user',
      parts: [{ text: `Post Context: ${visualContext}\n\nQuestion: ${userQuestion}` }]
    }]
  });
  return result.text;
}

// --- PDF & Email Logic ---
function createPDFBuffer(textContext, sourceUrl) {
  return new Promise((resolve, reject) => {
    // Set standard A4 size and clean margins
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers = [];

    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // ==========================================
    // 1. TEXT CLEANUP & FORMATTING
    // ==========================================
    // Cut off the hidden memory context so the user doesn't see it
    let publicText = textContext.split('--- HIDDEN CONTEXT ---')[0].trim();
    
    // Clean up Markdown formatting for the PDF
    publicText = publicText.replace(/\*\*/g, ''); // Remove the ** bold markers
    publicText = publicText.replace(/^\s*\*\s/gm, '  •  '); // Turn * into actual bullet points
    publicText = publicText.replace(/^\s*\d+\.\s/gm, match => `\n${match}`); // Add breathing room above numbered lists

    // ==========================================
    // 2. DOCUMENT DESIGN
    // ==========================================
    // Professional Header
    doc.fontSize(22)
       .font('Helvetica-Bold')
       .fillColor('#2C3E50') // Dark slate blue/grey
       .text('Describer Analysis Report', { align: 'center' });
       
    doc.moveDown(0.5);

    // Clickable Source Link
    doc.fontSize(10)
       .font('Helvetica-Oblique')
       .fillColor('#2980B9') // Bright blue
       .text(`Source: ${sourceUrl}`, { 
         align: 'center', 
         link: sourceUrl, 
         underline: true 
       });
       
    doc.moveDown(2);
    
    // Clean Body Text
    doc.fontSize(11)
       .font('Helvetica')
       .fillColor('#333333') // Soft black for better readability
       .text(publicText, {
         align: 'left',
         lineGap: 5,        // Space between lines
         paragraphGap: 12   // Space between paragraphs
       });

    // Footer
    doc.fontSize(9)
       .font('Helvetica-Oblique')
       .fillColor('#BDC3C7')
       .text('Generated by Describer AI', 50, doc.page.height - 50, { 
         align: 'center',
         lineBreak: false
       });

    // Finalize the PDF file
    doc.end();
  });
}
// --- Execution Logic (Triggered after the 3-second wait) ---
async function processInstagramPost(chatId, userId, instagramUrl, userInstruction) {
  try {
    bot.sendMessage(chatId, userInstruction ? `🎯 Answering: "${userInstruction}"` : "🔬 Analyzing post...");

    const igData = await instagramGetUrl(instagramUrl, process.env.IG_SESSION_ID);
    const base64Images = [];
    const media = (igData.url_list || []).slice(0, 5);

    for (const url of media) {
      if (url.includes('.mp4')) continue;
      const res = await fetch(url);
      const buf = await res.arrayBuffer();
      base64Images.push(Buffer.from(buf).toString('base64'));
    }

    if (base64Images.length === 0) return bot.sendMessage(chatId, "⚠️ No images found in this link.");

    const finalResponse = await analyzeVision(base64Images, userInstruction);
    
    // Save to memory
    userMemory.set(userId, { url: instagramUrl, visualDescription: finalResponse });
    await sendSafeMessage(chatId, finalResponse);

  } catch (error) {
    console.error("PROCESS ERROR:", error);
    bot.sendMessage(chatId, "❌ Request failed. Ensure the link is public.");
  }
}

// --- 2. Main Handler & Waiting Room ---
bot.on('message', async (msg) => {
  const chatId = msg.chat.id;
  const userId = msg.from.id;
  const text = msg.text || '';

  if (text === '/start') { stoppedUsers.delete(chatId); return bot.sendMessage(chatId, "✅ Active."); }
  if (text === '/stop') { stoppedUsers.add(chatId); return bot.sendMessage(chatId, "🛑 Stopped."); }
  if (stoppedUsers.has(chatId)) return;

  // --- PDF Export Command ---
  // Matches exactly "/email someone@domain.com"
  const emailMatch = text.match(/^\/email\s+([^\s@]+@[^\s@]+\.[^\s@]+)/i);
  
  if (emailMatch) {
    const userEmail = emailMatch[1];
    
    if (!userMemory.has(userId)) {
      return bot.sendMessage(chatId, "⚠️ I don't have any recent analysis in memory. Please send an Instagram link first.");
    }

    bot.sendChatAction(chatId, 'upload_document');
    bot.sendMessage(chatId, `⏳ Generating PDF and sending to ${userEmail}...`);

    try {
      const memory = userMemory.get(userId);
      const pdfBuffer = await createPDFBuffer(memory.visualDescription, memory.url);

      await transporter.sendMail({
        from: `"Describer AI" <${process.env.EMAIL_USER}>`,
        to: userEmail,
        subject: 'Your Instagram Analysis Report',
        text: 'Attached is the PDF report generated by Describer.',
        attachments: [
          {
            filename: 'Describer_Report.pdf',
            content: pdfBuffer 
          }
        ]
      });

      return bot.sendMessage(chatId, "✅ PDF successfully sent to your email!");
    } catch (error) {
      console.error("EMAIL ERROR:", error);
      return bot.sendMessage(chatId, "❌ Failed to send the email. Please check the address and try again.");
    }
  }

  // A. Follow-up Feature (Replying to an old bot message)
  if (msg.reply_to_message && userMemory.has(userId)) {
    bot.sendChatAction(chatId, 'typing');
    try {
      const memory = userMemory.get(userId).visualDescription;
      const response = await analyzeText(memory, text.trim());
      return await sendSafeMessage(chatId, response);
    } catch (err) {
      console.error(err);
      return bot.sendMessage(chatId, "❌ Failed to process follow-up.");
    }
  }

  // B. New Link Detection (Starts the 3-second timer)
  const linkMatch = text.match(/(https?:\/\/(?:www\.)?instagram\.com[^\s]+)/);

  if (linkMatch) {
    const url = linkMatch[0];
    const initialInstruction = text.replace(url, '').trim();

    // Clear existing timer if user sends another link quickly
    if (pendingRequests.has(userId)) clearTimeout(pendingRequests.get(userId).timer);

    bot.sendChatAction(chatId, 'typing'); // Show the user we saw it

    // Create the 3-second waiting room
    const timer = setTimeout(() => {
      const finalData = pendingRequests.get(userId);
      pendingRequests.delete(userId); // Empty the waiting room
      
      // Send the merged data to the Execution logic
      processInstagramPost(chatId, userId, finalData.url, finalData.instruction);
    }, 3000);

    // Save the link, any initial text, and the timer to the buffer
    pendingRequests.set(userId, { url, instruction: initialInstruction, timer });

  } 
  // C. Text Merging (If a link is already waiting in the 3-second room)
  else if (pendingRequests.has(userId)) {
    const pendingData = pendingRequests.get(userId);
    
    // Glue the newly forwarded text to the instructions already waiting
    pendingData.instruction = pendingData.instruction
      ? `${pendingData.instruction} ${text.trim()}`
      : text.trim();
    
    // The timer will naturally finish and use this newly combined text!
  }
});

const app = express();
app.get('/', (req, res) => res.send('Active'));
app.listen(process.env.PORT || 3000);