const PDFDocument = require("pdfkit");

const createPDFBuffer = (text, sourceUrl) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            margin: 50,
            size: "A4"
        });

        const buffers = [];

        doc.on("data", (chunk) => buffers.push(chunk));
        doc.on("end", () => resolve(Buffer.concat(buffers)));
        doc.on("error", reject);

        // Clean Markdown formatting for the PDF
        let publicText = text.trim();

        publicText = publicText.replace(/\*\*/g, "");
        publicText = publicText.replace(/^\s*\*\s/gm, "  •  ");
        publicText = publicText.replace(/^\s*-\s/gm, "  •  ");
        publicText = publicText.replace(
            /^\s*\d+\.\s/gm,
            (match) => `\n${match}`
        );

        // Header
        doc
            .fontSize(22)
            .font("Helvetica-Bold")
            .fillColor("#2C3E50")
            .text("Describer Analysis Report", {
                align: "center"
            });

        doc.moveDown(0.5);

        // Source URL
        doc
            .fontSize(10)
            .font("Helvetica-Oblique")
            .fillColor("#2980B9")
            .text(`Source: ${sourceUrl}`, {
                align: "center",
                link: sourceUrl,
                underline: true
            });

        doc.moveDown(2);

        // Analysis
        doc
            .fontSize(11)
            .font("Helvetica")
            .fillColor("#333333")
            .text(publicText, {
                align: "left",
                lineGap: 5,
                paragraphGap: 12
            });

        // Footer
        doc
            .fontSize(9)
            .font("Helvetica-Oblique")
            .fillColor("#BDC3C7")
            .text(
                "Generated by Describer AI",
                50,
                doc.page.height - 50,
                {
                    align: "center",
                    lineBreak: false
                }
            );

        doc.end();
    });
};

module.exports = {
    createPDFBuffer
};