const { Resend } = require("resend");
const { resendApiKey } = require("../config/env");

const resend = new Resend(resendApiKey);

const sendAnalysisEmail = async ({ to, pdfBuffer }) => {
    return resend.emails.send({
        from: "Describer AI <onboarding@resend.dev>",
        to,
        subject: "Your Instagram Analysis Report",
        text: "Attached is the PDF report generated by Describer.",
        attachments: [
            {
                filename: "Describer_Report.pdf",
                content: pdfBuffer
            }
        ]
    });
};

module.exports = {
    sendAnalysisEmail
};